<?php
// $Id$

/**
 * @file Rules Web Test Module.
 */

/**
 * Implementation of hook_default_rules_web_remote().
 */
function rules_taxonomy_sync_slave_default_rules_web_remote() {
  $remote = new RulesWebRemote();
  $remote->name = 'term_master';
  $remote->label = 'The taxonomy master';
  $remote->url = variable_get('rules_taxonomy_sync_master_url', FALSE);
  $remote->type = 'rules_web_hook';
  $remote->settings['curl options'] = array(
    CURLOPT_SSL_VERIFYPEER => FALSE, // For testing skip ssl verification.
    CURLOPT_SSL_VERIFYHOST => FALSE, // For testing skip ssl verification.
  );
  // Hack: Use the same auth as for this site for the remote.
  if ($auth = rules_web_remote_get_http_auth()) {
    $remote->settings['curl options'][CURLOPT_USERPWD] = !empty($auth['username']) ? $auth['username'] . ':' . $auth['password'] : '';
    $remote->settings['curl options'][CURLOPT_HTTPAUTH] = !empty($auth['method']) ? (int)$auth['method'] : '';
  }
  if ($remote->url) {
    $remotes[$remote->name] = $remote;
    return $remotes;
  }
}

/**
 * Implements hook_default_rules_configuration().
 */
function rules_taxonomy_sync_slave_default_rules_configuration() {
  $vocab = reset(taxonomy_vocabulary_load_multiple(FALSE, array('machine_name' => 'rules_taxonomy_sync')));

  $rule = rules_reaction_rule();
  $rule->label = 'Create local copy of term';
  $rule->active = TRUE;
  $rule->event('rules_web_term_master_term_insert')
       ->action('data_fetch', array('type' => 'taxonomy_vocabulary', 'param_id' => $vocab->vid))
       ->action('data_create', array(
         'type' => 'taxonomy_term',
         'param_name:select' => 'term:name',
         'param_vocabulary:select' => 'data_fetched'
       ));
  $configs['rules_taxonomy_sync_slave_insert'] = $rule;
  
  return $configs;
}

/**
 * Implements hook_install().
 */
function rules_taxonomy_sync_slave_install() {
  if (!variable_get('rules_taxonomy_sync_master_url', FALSE)) {
    drupal_set_message(t('Be sure to set the variable %name to the url of the master site - then refresh caches or reinstall the module.', array('%name' => 'rules_taxonomy_sync_master_url')));
  }
  $vocabulary = (object) array(
    'name' => 'Rules Synced Taxonomy',
    'hierarchy' => TRUE,
    'description' => '',
    'machine_name' => 'rules_taxonomy_sync',
    'help' => '',
  );
  taxonomy_vocabulary_save($vocabulary);
}
